### ISSUE TITLE
Version bump to be compatible with Terminus 2.4.1

### ISSUE THREAD

**Issue by carl-alberto** [geraldvillorente/terminus-site-debug#2]
Getting errors like:

In ComposerDependencyValidator.php line 120:
                                                                                      
  The plugin geraldvillorente/terminus-site-debug has installed the project psr/log:  
   1.1.0, but Terminus has installed psr/log: 1.1.3. To resolve this, try running 'c  
  omposer update' in both the plugin directory, and the terminus directory.           

The plugin geraldvillorente/terminus-site-debug has installed the project squizlab  
  s/php_codesniffer: 3.5.6, but Terminus has installed squizlabs/php_codesniffer: 3.  
  5.5. To resolve this, try running 'composer update' in both the plugin directory,   
  and the terminus directory.

**Comment by pwtyler** [comment]
@carl-alberto, is this issue still outstanding?

**Comment by carl-alberto** [comment]
This seems to be fixed from here https://github.com/pantheon-systems/terminus-site-debug/pull/3
